### PR TITLE
Allowing the use of an existing database/sql pool

### PR DESCRIPTION
**Pull request by caarlos0**
refs #10.

If you think it's not, please suggest a name for the function that don't create a new pool (because I cannot think in any :baby_chick: )

Thanks

### CODE REVIEW

**Comment by antonlindstrom** [comment]
> This feature will break the API...

Is this really a breaking change?

**Comment by caarlos0** [comment]
It was, but I changed it so now it isn't anymore

**Comment by antonlindstrom** [comment]
> It was, but I changed it so now it isn't anymore

Awesome! I think this is good. Update the comments and commit message to remove "breaking change" and I'll go ahead and merge. :bow: 

Thanks!

**Comment by caarlos0** [comment]
@antonlindstrom done

**Comment by antonlindstrom** [comment]
@caarlos0 Awesome, thanks! :bow:

**Pull request merged**
